name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Android SDK + accept licenses
      - uses: android-actions/setup-android@v3

      # Use hosted Gradle (no gradlew wrapper needed)
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6

      - name: Build release APK
        run: gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuestARLauncher-APK
          path: app/build/outputs/apk/release/*.apk
